# -*- coding: utf-8 -*-
"""advance python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojMTqd6oIp-Uvvktvdrx9TXY7e0KKgbu
"""

balance = 0
transactions = []

while True:
    print("\n1. Deposit")
    print("2. Withdraw")
    print("3. Balance")
    print("4. Transactions")
    print("5. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        amt = float(input("Enter amount: "))
        balance += amt
        transactions.append("Deposited: " + str(amt))
        print("Money deposited")

    elif choice == "2":
        amt = float(input("Enter amount: "))
        if amt <= balance:
            balance -= amt
            transactions.append("Withdrawn: " + str(amt))
            print("Money withdrawn")
        else:
            print("Not enough balance")

    elif choice == "3":
        print("Balance:", balance)

    elif choice == "4":
        print("Transactions:")
        for t in transactions:
            print(t)

    elif choice == "5":
        print("Thank you!")
        break

    else:
        print("Invalid choice")

users = {}
participants = set()
5
while True:
    print("\n--- EVENT TRACKER ---")
    print("1. Register")
    print("2. Login")
    print("3. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        username = input("Enter username: ")

        if username in users:
            print("Username already exists")
        else:
            password = input("Enter password: ")
            users[username] = password
            print("Registration successful")

    elif choice == "2":
        username = input("Username: ")
        password = input("Password: ")

        if users.get(username) == password:
            print("Login successful")

            while True:
                print("\n1. Add participant")
                print("2. Remove participant")
                print("3. View participants")
                print("4. Logout")

                ch = input("Enter choice: ")

                if ch == "1":
                    name = input("Participant name: ")
                    participants.add(name)
                    print("Added")

                elif ch == "2":
                    name = input("Participant name: ")
                    participants.discard(name)
                    print("Removed (if existed)")

                elif ch == "3":
                    print("Participants:", participants)

                elif ch == "4":
                    print("Logged out")
                    break

                else:
                    print("Invalid option")

        else:
            print("Wrong username or password")

    elif choice == "3":
        print("Goodbye")
        break

    else:
        print("Invalid choice")

rooms = {
    101: None, 102: None, 103: None, 104: None, 105: None,
    106: None, 107: None, 108: None, 109: None, 110: None
}

n = int(input("Enter number of students: "))

for i in range(n):
    name = input("Enter student name: ")
    allotted = False

    for room in rooms:
        if rooms[room] is None:
            rooms[room] = name
            print(name, "allotted room", room)
            allotted = True
            break

    if not allotted:
        print("Sorry, all rooms are occupied")
        break

print("\nFinal Room Allotment:")
for room, student in rooms.items():
    print(room, ":", student)

"""Questions of sets"""

a = [1, 2, 3, 4]
b = [3, 4, 5]

print(set(a) & set(b))

s = "python is easy and python is fun"
print(" ".join(set(s.split())))

a = "listen"
b = "silent"

print(set(a) == set(b) and len(a) == len(b))

a = [1, 2, 3, 4]
b = [3, 4]

print(set(a) - set(b))

s = "python"
print(len(s) == len(set(s)))

a = [1, 2, 2, 3, 4, 4]
print(len(set(a)))

a = {1, 2, 3}
b = {3, 4, 5}

result = set()
for i in a:
    if i not in b:
        result.add(i)
for i in b:
    if i not in a:
        result.add(i)

print(result)

a = "hello"
b = "world"

print(set(a) - set(b))
print(set(b) - set(a))

a = {1, 2}
b = {1, 2, 3}

is_subset = True
for i in a:
    if i not in b:
        is_subset = False

print(is_subset)

a = [1, 2, 2, 3, 4, 4]
seen = set()
repeated = set()

for i in a:
    if i in seen:
        repeated.add(i)
    else:
        seen.add(i)

print(repeated)

"""ATM system using multiple accounts

"""

accounts = {
    "101": {"pin": "1111", "balance": 5000},
    "102": {"pin": "2222", "balance": 3000},
    "103": {"pin": "3333", "balance": 7000}
}

while True:
    print("\n--- ATM ---")
    acc_no = input("Enter Account Number: ")
    pin = input("Enter PIN: ")

    if acc_no in accounts and accounts[acc_no]["pin"] == pin:
        print("Login Successful!")

        while True:
            print("\n1. Deposit")
            print("2. Withdraw")
            print("3. Balance")
            print("4. Exit")

            choice = input("Enter choice: ")

            if choice == "1":
                amt = float(input("Enter amount: "))
                accounts[acc_no]["balance"] += amt
                print("Money Deposited")

            elif choice == "2":
                amt = float(input("Enter amount: "))
                if amt <= accounts[acc_no]["balance"]:
                    accounts[acc_no]["balance"] -= amt
                    print("Money Withdrawn")
                else:
                    print("Insufficient Balance")

            elif choice == "3":
                print("Balance:", accounts[acc_no]["balance"])

            elif choice == "4":
                print("Thank You!")
                break

            else:
                print("Invalid choice")
    else:
        print("Invalid Account Number or PIN")

    again = input("\nDo you want to continue? (yes/no): ")
    if again.lower() != "yes":
        break

"""Student Grade book"""

grade_book = {}

while True:
    print("\n1. Add Student")
    print("2. View Student Grade")
    print("3. View All Students")
    print("4. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        name = input("Enter student name: ")
        marks = float(input("Enter marks: "))
        grade_book[name] = marks
        print("Student added successfully")

    elif choice == "2":
        name = input("Enter student name: ")
        if name in grade_book:
            print(name, "marks:", grade_book[name])
        else:
            print("Student not found")

    elif choice == "3":
        print("\nAll Students:")
        for name, marks in grade_book.items():
            print(name, ":", marks)

    elif choice == "4":
        print("Goodbye!")
        break

    else:
        print("Invalid choice")

"""Using functions"""

balance = 0
transactions = []

def deposit():
    global balance
    amt = float(input("Enter amount: "))
    balance += amt
    transactions.append("Deposited: " + str(amt))
    print("Money deposited")

def withdraw():
    global balance
    amt = float(input("Enter amount: "))
    if amt <= balance:
        balance -= amt
        transactions.append("Withdrawn: " + str(amt))
        print("Money withdrawn")
    else:
        print("Not enough balance")

def show_balance():
    print("Balance:", balance)

def show_transactions():
    print("Transactions:")
    for t in transactions:
        print(t)

def atm():
    while True:
        print("\n1. Deposit")
        print("2. Withdraw")
        print("3. Balance")
        print("4. Transactions")
        print("5. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            deposit()
        elif choice == "2":
            withdraw()
        elif choice == "3":
            show_balance()
        elif choice == "4":
            show_transactions()
        elif choice == "5":
            print("Thank you!")
            break
        else:
            print("Invalid choice")

atm()

def main():
    users = {}
    participants = set()

    def register():
        username = input("Enter username: ")
        if username in users:
            print("Username already exists")
        else:
            password = input("Enter password: ")
            users[username] = password
            print("Registration successful")

    def login():
        username = input("Username: ")
        password = input("Password: ")

        if users.get(username) == password:
            print("Login successful")
            participant_menu()
        else:
            print("Wrong username or password")

    def participant_menu():
        while True:
            print("\n1. Add\n2. Remove\n3. View\n4. Logout")
            ch = input("Enter choice: ")

            if ch == "1":
                participants.add(input("Participant name: "))
                print("Added")
            elif ch == "2":
                participants.discard(input("Participant name: "))
                print("Removed")
            elif ch == "3":
                print("Participants:", participants)
            elif ch == "4":
                break
            else:
                print("Invalid option")

    while True:
        print("\n1. Register\n2. Login\n3. Exit")
        choice = input("Enter choice: ")

        if choice == "1":
            register()
        elif choice == "2":
            login()
        elif choice == "3":
            print("Goodbye")
            break
        else:
            print("Invalid choice")

main()

def main():
    rooms = {
        101: None, 102: None, 103: None,
        104: None, 105: None, 106: None
    }

    n = int(input("Enter number of students: "))

    for i in range(n):
        name = input("Enter student name: ")
        allotted = False

        for room in rooms:
            if rooms[room] is None:
                rooms[room] = name
                print(name, "allotted room", room)
                allotted = True
                break

        if not allotted:
            print("Sorry, all rooms are occupied")
            break

    print("\nFinal Room Allotment:")
    for room, student in rooms.items():
        print(room, ":", student)

main()